language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov pytest
  - pip install codecov
# command to run tests
script:
  - py.test --cov-report term --cov=objects/test/
after_success:
  - codecov
#  - bash <(curl -s https://codecov.io/bash)
