language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
# command to run tests
script:
  - coverage run test
after_success:
  #- codecov
  - bash <(curl -s https://codecov.io/bash)
