language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls-python
script:
  - coverage run -m pytest
  - coverage report -m
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
