
version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/objects
    docker:
      - image: cimg/python:3.6
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Setup testing environment
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov
  done:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - coveralls/upload:
          parallel_finished: true
workflows:
  test_objects:
    jobs:
      - build
      - done:
          requires:
            - build

# notify:
#   webhooks:
#     - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
