version: 2.1
orbs:
  python: circleci/python@1.0
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/objects
    docker:
      - image: cimg/python:3.6-node
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Setup testing environment
          command: |
            pip install -r requirements.txt
            pip install coverage-lcov
      - run:
          name: Run Tests
          command: |
            mkdir coverage/
            coverage run -m pytest
            coverage report
            coverage html
            coverage-lcov --data_file_path .coverage
            coverage-lcov --output_file_path coverage/lcov.info
            npm install nyc coveralls
            echo repo_token: $COVERALLS_REPO_TOKEN > ./.coveralls.yml

      - coveralls/upload
      # - coveralls/upload:
      #     path_to_lcov: htmlcov/status.json
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: coverage/lcov.info
      - store_artifacts:
          path: .coverage

#   done:  # needs the artifact from build
#    docker:
#      - image: circleci/node:10.0.0
#      # - image: cimg/python:3.6
#    steps:
#      - coveralls/upload:
#          parallel_finished: true
# workflows:
#   test_objects:
#     jobs:
#       - build
#       - done:
#           requires:
#             - build
#
# notify:
#   webhooks:
#     - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
