version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/objects
    docker:
      - image: cimg/python:3.6-node
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Setup testing environment
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            mkdir coverage/
            touch coverage/lcov.info
            coverage run -m pytest
            coverage report > ./coverage/lcov.info
            coverage html
      #       mkdir test-results
      #       pytest --junitxml=test-results/junit.xml
      #
      # - store_test_results:
      #     path: test-results
      #
      # - store_artifacts:
      #     path: test-results
      - coveralls/upload
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: .coverage
      - store_artifacts:
          path: ./coverage/lcov.info
      # - coveralls/upload:
      #     file: htmlcov/index.html
      # - store_artifacts: # upload test coverage as artifact
      #     path: ./coverage/lcov.info
      #     prefix: tests
#   done:
#    docker:
#      - image: circleci/node:10.0.0
#      # - image: cimg/python:3.6
#    steps:
#      - coveralls/upload:
#          parallel_finished: true
# workflows:
#   test_objects:
#     jobs:
#       - build
#       - done:
#           requires:
#             - build
#
# notify:
#   webhooks:
#     - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
